urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='recipes'
urlpatterns = [
    path('', views. HomePage.as_view(), name='home_page'),
    path('recipes', views.RecipeListView.as_view(), name='all'),
    path('recipes/<int:pk>', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipes/create',
        views.RecipeCreateView.as_view(success_url=reverse_lazy('recipes:all')), name='recipe_create'),
    path('recipes/<int:pk>/update',
        views.RecipeUpdateView.as_view(success_url=reverse_lazy('recipes:all')), name='recipe_update'),
    path('recipes/<int:pk>/delete',
        views.RecipeDeleteView.as_view(success_url=reverse_lazy('recipes:all')), name='recipe_delete'),
    path('your_recipes', views.UserRecipeListView.as_view(), name='user_recipe_list'),

    path('recipe_picture/<int:pk>', views.stream_file, name='recipe_picture'),
    path('recipe/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='recipe_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('recipes')), name='recipe_comment_delete'),
    path('recipe/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='recipe_favorite'),
    path('recipe/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='recipe_unfavorite'),

    path('recipe/<int:pk>/ingredient', views.IngredientCreateView.as_view(), name='recipe_ingredient_create'),
    path('ingredient/<int:pk>/delete', views.IngredientDeleteView.as_view(), name='recipe_ingredient_delete'),

]

templates/recipes/home_page.html
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">

    <title>Recipes for All</title>
</head>
<body style="font-family: Georgia;">
    <header>
        <h1>Recipes for All</h1>
        <nav>
            <ul>
                <li class="nav-li active"><a href="{% url 'recipes:home_page' %}">Home</a></li>
                <li class="nav-li"><a href="{% url 'recipes:all' %}">Recipes</a></li>
                <li class="nav-li"><a href="{% url 'recipes:user_recipe_list' %}">Your Recipes</a></li>
                <li class="nav-li">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}?next={% url 'recipes:home_page' %}">Logout</a>
                    {% else %}
                    <a href="{% url 'login' %}?next={% url 'recipes:home_page' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>

    <p style="font-size: 150%; color: #555555;">Welcome to Recipes for All, the recipe website where recipes are uploaded by anyone, for everyone! </p>

    <h2 style="font-size: 200%;">Recently Added: </h2>
    {% for recipe in recipe_list reversed %}
        {% if forloop.counter < 5 %}
        <li style="width: 20%;" class="recipe-detail">
            <h3 style="font-size: 150%;"><a class="recipe-title" href="{% url 'recipes:recipe_detail'  recipe.id %}">{{ recipe.title }}</a></h3>
            {% if recipe.content_type %}
            <img style="display: block; margin-left: auto; margin-right: auto; max-width:90%;" src="{% url 'recipes:recipe_picture' recipe.id %}"
                onclick="document.getElementById('overlay').style.display = 'block';">
            {% endif %}
            <p style="text-align:center; color: #555555; padding: 5px;">{{recipe.description}}</p>
            <br clear="all"/>
            <div class="edit-delete">
        </li>
        {% endif %}
</body>
{% endfor %}
{% endblock %}

templates/recipes/recipe_comment_delete.html
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <title>Recipes for All</title>
</head>
<!--<header>-->
<!--    <h1>Recipes for All</h1>-->
<!--    <nav>-->
<!--        <ul>-->
<!--            <li class="nav-li"><a href="{% url 'recipes:home_page' %}">Home</a></li>-->
<!--            <li class="nav-li"><a href="{% url 'recipes:all' %}">Recipes</a></li>-->
<!--            <li class="nav-li"><a href="{% url 'recipes:user_recipe_list' %}">Your Recipes</a></li>-->
<!--            <li class="nav-li">-->
<!--                {% if user.is_authenticated %}-->
<!--                <a href="{% url 'logout' %}?next={% url 'recipes:all' %}">Logout</a>-->
<!--                {% else %}-->
<!--                <a href="{% url 'login' %}?next={% url 'recipes:all' %}">Login</a>-->
<!--                {% endif %}-->
<!--            </li>-->
<!--        </ul>-->
<!--    </nav>-->
<!--</header>-->

<h2>Delete Comment</h2>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'recipes:recipe_detail' comment.recipe.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/recipes/recipe_confirm_delete.html
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <title>Recipes for All</title>
</head>
<header>
    <h1>Recipes for All</h1>
    <nav>
        <ul>
            <li class="nav-li"><a href="{% url 'recipes:home_page' %}">Home</a></li>
            <li class="nav-li"><a href="{% url 'recipes:all' %}">Recipes</a></li>
            <li class="nav-li"><a href="{% url 'recipes:user_recipe_list' %}">Your Recipes</a></li>
            <li class="nav-li">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}?next={% url 'recipes:all' %}">Logout</a>
                {% else %}
                <a href="{% url 'login' %}?next={% url 'recipes:all' %}">Login</a>
                {% endif %}
            </li>
        </ul>
    </nav>
</header>

<h2>Delete Recipe</h2>

<p>Are you sure you want to delete the recipe: {{ recipe }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

templates/recipes/recipe_detail.html
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% load static %}
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}

.control-label{
    font-size: 125%;
    font-weight: bold;
}

#detail-body{
    color: #555555;
}

.detail-heading{
    color: #000000;
}

main{
    font-family: Georgia;
}
</style>

{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
    <title>Recipes for All</title>
</head>
<main>
    <header>
        <h1>Recipes for All</h1>
        <nav>
            <ul>
                <li class="nav-li"><a href="{% url 'recipes:home_page' %}">Home</a></li>
                <li class="nav-li"><a href="{% url 'recipes:all' %}">Recipes</a></li>
                <li class="nav-li"><a href="{% url 'recipes:user_recipe_list' %}">Your Recipes</a></li>
                <li class="nav-li">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}?next={% url 'recipes:all' %}">Logout</a>
                    {% else %}
                    <a href="{% url 'login' %}?next={% url 'recipes:all' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>
    {% if user.is_authenticated %}

    {% if recipe.content_type %}
    <div id="overlay" class="overlay" style="text-align: center;"
       onclick="document.getElementById('overlay').style.display = 'none';" >
    <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'recipes:recipe_picture' recipe.id %}">
    </div>
    {% endif %}
    <span style="float: right;">
    ({{ recipe.updated_at|naturaltime }})
    {% if recipe.owner == user %}
    <a style="color: #555555;" href="{% url 'recipes:recipe_update' recipe.id %}"><i class="fa fa-pencil"></i></a>
    <a style="color: #555555;" href="{% url 'recipes:recipe_delete' recipe.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
    </span>

    <button style="margin-top:10px;"><a style="color: #FFFFFF;" href="{% url 'recipes:all' %}">All Recipes</a></button>

    <h2 style="font-size: 250%; margin-top: 5px;">{{ recipe.title }}</h2>
    {% if recipe.content_type %}
    <img style="float:right; max-width:50%;" src="{% url 'recipes:recipe_picture' recipe.id %}"
        onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}
    <div id="detail-body">
    <h4 class ="detail-heading" style="font-size: 150%;">Description: </h4>
    <p>
        {{ recipe.description }}
    </p>

    <h4 class ="detail-heading" style="font-size: 150%;">Ingredients: </h4>

    {% for ingredient in ingredients %}
        <p style="margin-left: 20px;">
            <span style="font-weight: bold;">{{ ingredient.name }}</span> - {{ingredient.measurement}}
            <!--<a style="color: #555555;" href=""><i class="fa fa-trash"></i></a> <!--{% url 'recipes:recipe_update' ingredient.recipe.id %}-->
        </p>
    {% endfor %}


    <h4 class ="detail-heading" style="font-size: 150%;">Instructions: </h4>

    <p>
        {{ recipe.instructions|linebreaks }}
    </p>
    </div>
    {% else %}
    <p style="font-size: 150%">Please login to view recipes</p>
    {% endif %}

    <br/>
    <br/>

    {% if user.is_authenticated %}
    <!--<br clear="all"/>-->
    <p>
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'recipes:recipe_comment_create' recipe.id %}">
        {% csrf_token %}
        {{ comment_form|crispy }}
    <input style="margin-top: 5px;" type="submit" value="Submit">
    <!--<input type="submit" value="All Recipes" onclick="window.location.href='{% url 'recipes:all' %}';return false;">-->
    </form>
    </p>
    {% endif %}
    {% for comment in comments %}
        <h6 style="margin:5px; font-size: 100%;">{{comment.owner}}</h6>
        <p style="color: #555555; margin: 5px 5px 20px 5px;"> {{ comment.text }}
        ({{ comment.updated_at|naturaltime }})
        {% if user == comment.owner %}
        <a style="color: #555555;" href="{% url 'recipes:recipe_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
        </p>
    {% endfor %}
</main>
{% endblock %}

templates/recipes/recipe_form.html
<!--{% extends "base_bootstrap.html" %}-->
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <title>Recipes for All</title>
</head>
<header id="form-header">
    <h1>Recipes for All</h1>
</header>


<h3>*Please note*: You can only add ingredients after you have created your recipe. When you are finished with the recipe, submit and and then click the edit button to add ingredients. Sorry for the inconvenience.</h3>
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <!--{{ value|linebreaksbr }}-->

    <input type="submit" value="Submit Recipe">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'recipes:all' %}';return false;">
  </form>
</p>


<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

templates/recipes/recipe_ingredient_delete.html
{% load static%}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <title>Recipes for All</title>
</head>
<header id="form-header">
    <h1>Recipes for All</h1>
</header>

<h2>Delete Ingredient</h2>

<p>Are you sure you want to delete</p>
<p>{{ ingredient.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'recipes:recipe_update' ingredient.recipe.id %}" class="btn btn-secondary">Cancel</a>

</form>
{% endblock %}

templates/recipes/recipe_list.html
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

    <script
    src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
    <title>Recipes for All</title>
</head>
<body style="font-family: Georgia;">
    <header>
        <h1>Recipes for All</h1>
        <nav>
            <ul>
                <li class="nav-li"><a href="{% url 'recipes:home_page' %}">Home</a></li>
                <li class="nav-li active"><a href="{% url 'recipes:all' %}">Recipes</a></li>
                <li class="nav-li"><a href="{% url 'recipes:user_recipe_list' %}">Your Recipes</a></li>
                <li class="nav-li">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}?next={% url 'recipes:home_page' %}">Logout</a>
                    {% else %}
                    <a href="{% url 'login' %}?next={% url 'recipes:home_page' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>

    <h2 style="font-size: 250%;">Recipes</h2>
    <button><a style="color: #FFFFFF;" href="{% url 'recipes:recipe_create' %}">Add a Recipe</a></button>
    <br clear="all"/>
    <h2>Search:</h2>
    <div>
         <!--https://www.w3schools.com/howto/howto_css_search_button.asp-->
        <form>
              <input style="width: 20%; border-radius: 10px; height: 30px; " type="text" placeholder="Search.." name="search"
              {% if search %} value="{{ search }}" {% endif %}
              >
              <button type="submit"><i style="color: #FFFFFF;" class="fa fa-search"></i></button>
            <a href="{% url 'recipes:all' %}"><i style="color: #555555; text-decoration: none;" class="fa fa-undo"></i></a>
        </form>
    </div>
    <div style="text-align:center;">
    {% if recipe_list %}

    {% for recipe in recipe_list %}
        <li stye="font-family: Georgia;" class="recipe-detail">
            <h3 class="heading-title" style="display: inline; font-size: 150%;"><a class="recipe-title" href="{% url 'recipes:recipe_detail'  recipe.id %}">{{ recipe.title }}</a></h3>
            {% if user.is_authenticated %}
            <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
            <a href="#" onclick=
                "favPost('{% url 'recipes:recipe_unfavorite' recipe.id %}', {{ recipe.id }} );return false;"
                {% if recipe.id not in favorites %} style="display: none;" {% endif %}
                id="favorite_star_{{recipe.id}}">
            <span class="fa-stack" style="vertical-align: middle;">
            <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
            <i class="fa fa-star-o fa-stack-1x"></i>
            </span>
            </a>
            <!-- the second href -->
            <a href="#" onclick=
                 "favPost('{% url 'recipes:recipe_favorite' recipe.id %}', {{ recipe.id }} );return false;"
                {% if recipe.id in favorites %} style="display: none;" {% endif %}
                id="unfavorite_star_{{recipe.id}}">
            <span class="fa-stack" style="vertical-align: middle;">
            <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
            <i class="fa fa-star-o fa-stack-1x"></i>
            </span>
            </a>
            {% endif %}
            {% if recipe.content_type %}
            <img style="display: block; margin-left: auto; margin-right: auto; max-width:90%;" src="{% url 'recipes:recipe_picture' recipe.id %}"
                onclick="document.getElementById('overlay').style.display = 'block';">
            {% endif %}
            <p style="text-align:center; color: #555555; padding: 5px;">{{recipe.description}}</p>
            <div class="edit-delete">
            {% if recipe.owner == user %}
            (<a href="{% url 'recipes:recipe_update' recipe.id %}">Edit</a> |
            <a href="{% url 'recipes:recipe_delete' recipe.id %}">Delete</a>)
            {% endif %}
            </div>
        </li>
      {% endfor %}
    {% else %}
      <p>There are no recipes available.</p>
    {% endif %}
    </div>
</body>

<script>
function favPost(url, recipe_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+recipe_id).toggle();
        $("#favorite_star_"+recipe_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

<!--<ul>-->
<!--  {% for recipe in recipe_list %}-->
<!--    <li>-->
<!--        <a href="{% url 'recipes:recipe_detail'  recipe.id %}">{{ recipe.title }}</a>-->
<!--        {% if recipe.owner == user %}-->
<!--        (<a href="{% url 'recipes:recipe_update' recipe.id %}">Edit</a> |-->
<!--        <a href="{% url 'recipes:recipe_delete' recipe.id %}">Delete</a>)-->
<!--        {% endif %}-->
<!--    </li>-->
<!--  {% endfor %}-->
<!--</ul>-->

templates/recipes/recipe_update.html
<!--{% extends "base_bootstrap.html" %}-->
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <title>Recipes for All</title>
</head>
<header id="form-header">
    <h1>Recipes for All</h1>
</header>

<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <!--{{ value|linebreaksbr }}-->

    <input type="submit" value="Submit Recipe">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'recipes:all' %}';return false;">
  </form>
</p>

{% if user.is_authenticated %}
    <!--<br clear="all"/>-->
    <p>
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'recipes:recipe_ingredient_create' recipe.id %}">
        {% csrf_token %}
        {{ ingredient_form|crispy }}
    <input type="submit" value="Submit Ingredient">
    </form>
    </p>
{% endif %}
{% for ingredient in ingredients %}
    <p style=""> {{ ingredient.name }} - {{ingredient.measurement}}
    <a style="color: #555555;" href="{% url 'recipes:recipe_ingredient_delete' ingredient.id %}"><i class="fa fa-trash"></i></a> <!--{% url 'recipes:recipe_update' ingredient.recipe.id %}-->
    <!--recipes:recipe_ingredient_delete-->
    </p>
{% endfor %}

<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

templates/recipes/user_recipe_list.html
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">
    <title>Recipes for All</title>
</head>
<body style="font-family: Georgia;">
<header>
    <h1>Recipes for All</h1>
    <nav>
        <ul class="nav-bar">
            <li class="nav-li"><a href="{% url 'recipes:home_page' %}">Home</a></li>
            <li class="nav-li"><a href="{% url 'recipes:all' %}">Recipes</a></li>
            <li class="nav-li active"><ahref="{% url 'recipes:user_recipe_list' %}">Your Recipes</a></li>
            <li class="nav-li">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}?next={% url 'recipes:home_page' %}">Logout</a>
                {% else %}
                <a href="{% url 'login' %}?next={% url 'recipes:home_page' %}">Login</a>
                {% endif %}
            </li>
        </ul>
    </nav>
</header>
<div style="width: 65%; float: left;" id="recipes-left">
<h2 style="font-size: 200%;">Your Recipes</h2>
<button><a style="color: #FFFFFF;" href="{% url 'recipes:recipe_create' %}">Add a Recipe</a></button>
<br clear="all"/>

{% if my_recipes %}

{% for recipe in my_recipes %}
    {% if recipe.owner == user %}
    <li style="width: 30%;" class="recipe-detail">
        <h3 style="font-size: 150%"><a class="recipe-title" href="{% url 'recipes:recipe_detail'  recipe.id %}">{{ recipe.title }}</a></h3>
        <div class="edit-delete">
        {% if recipe.owner == user %}
        (<a href="{% url 'recipes:recipe_update' recipe.id %}">Edit</a> |
        <a href="{% url 'recipes:recipe_delete' recipe.id %}">Delete</a>)
        {% endif %}
        </div>
        {% if recipe.content_type %}
        <img style="display: block; margin-left: auto; margin-right: auto; max-width:90%;" src="{% url 'recipes:recipe_picture' recipe.id %}"
            onclick="document.getElementById('overlay').style.display = 'block';">
        {% endif %}
        <p style="text-align:center; color: #555555; padding: 5px;">{{recipe.description}}</p>
    </li>
    {% endif %}
{% endfor %}
{% else %}
  <p>You have not input any recipes</p>
{% endif %}
</div>

<div style="width: 34%; float: right; border: solid 2px #555555; border-radius: 10px; margin: 5px; text-align: center;" id="recipes-right">
    <h2 style="font-size: 175%; margin-left: 5px;">Your Favorites</h2>
    {% for recipe in my_recipes %}
    {% if recipe.id in favorites %}
        <li style="width: 45%;" class="recipe-detail">
            <h3><a class="recipe-title" href="{% url 'recipes:recipe_detail'  recipe.id %}">{{ recipe.title }}</a></h3>
            <div class="edit-delete">
            {% if recipe.owner == user %}
            (<a href="{% url 'recipes:recipe_update' recipe.id %}">Edit</a> |
            <a href="{% url 'recipes:recipe_delete' recipe.id %}">Delete</a>)
            {% endif %}
            </div>
            {% if recipe.content_type %}
            <img style="display: block; margin-left: auto; margin-right: auto; max-width:90%;" src="{% url 'recipes:recipe_picture' recipe.id %}"
                onclick="document.getElementById('overlay').style.display = 'block';">
            {% endif %}
            <p style="text-align:center; color: #555555; padding: 5px;">{{recipe.description}}</p>
        </li>
    {% endif %}
    {% endfor %}
</div>
</body>

{% endblock %}